'use client';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useToast } from '@/hooks/use-toast';
import { user } from '@/lib/data';
import { Copy, HeartHandshake, Users } from 'lucide-react';
import { StatCard } from '@/components/profile/stat-card';

export default function ReferralsPage() {
  const { toast } = useToast();
  const referralLink = `https://tongifts.com/join?ref=${user.username}`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(referralLink);
    toast({
      title: 'Copied to clipboard!',
      description: 'Your referral link is ready to be shared.',
    });
  };

  return (
    <div className="container mx-auto py-8 px-4 sm:px-6 lg:px-8">
      <h1 className="text-4xl font-headline font-bold text-foreground mb-8">
        Invite Friends, Earn Rewards
      </h1>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <Card className="md:col-span-2">
          <CardHeader>
            <CardTitle className="font-headline">Your Referral Link</CardTitle>
            <CardDescription>
              Share this link with your friends. You'll earn cashback on their
              trading volume!
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex gap-2">
              <Input readOnly value={referralLink} />
              <Button onClick={copyToClipboard} size="icon" aria-label="Copy link">
                <Copy className="h-4 w-4" />
              </Button>
            </div>
          </CardContent>
        </Card>

        <StatCard
          icon={Users}
          title="Friends Joined"
          value={user.referrals.toString()}
          description="Total friends who joined via your link"
        />

        <StatCard
          icon={HeartHandshake}
          title="Friends' Volume"
          value={`$${user.friendsVolume.toLocaleString()}`}
          description="Total volume generated by your friends"
          color="text-yellow-400"
        />
      </div>
    </div>
  );
}
